development:
    access_key_id: 
    secret_access_key: 
    bucket: "fb_classified_development"
test:
    access_key_id: 
    secret_access_key: 
    bucket: "fb_classified_test"
production:
    access_key_id: AKIAJHMJJMZ6NFLGUC6A
    secret_access_key: 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
    bucket: fb-classifieds